name: Simple File Storage Workflow

# 触发事件
on:
  push:
    branches:
      - main  # 每次推送到 main 分支时触发
  pull_request:
    branches:
      - main  # 每次创建 PR 到 main 分支时触发

jobs:
  file-management:
    runs-on: ubuntu-latest  # 在 Ubuntu 环境中运行

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # 检出仓库中的代码文件

    - name: Print files
      run: |
        echo "Files in the repository:"
        ls -l  # 列出仓库中的文件，便于查看更新
